version: '3.7'

services:
  server:
    build:
      context: ""
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm run start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB

    networks:
      - app-network
  mongo:
    image: mongo:4.4.6
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ../client
      dockerfile: ../client/Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm run start
    volumes:
      - ../client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
      driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local

